// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from '@prisma/config';

export default defineConfig({
  schema: './prisma/schema.prisma',
  datasource: {
    // Migrate uses this URL directly; port 5432 is required
    url: process.env.DIRECT_URL,
    directUrl: process.env.DIRECT_URL,
  },
});